variable "vpc_cidr" {}
variable "env" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "azs" {}
variable "default_vpc_id" {}
variable "account_no" {}
variable "default_vpc_cidr" {}
variable "default_route_table_id" {}
variable "alb_type" {}
variable "internal" {}
variable "alb_sg_allow_cidr" {}
variable "subnets" {}
variable "vpc_id" {}
variable "tg_arn" {}
variable "region" {}
variable "component" {}
variable "app_port" {}
